//--- BL1P's bitchen VA Whitelist Array

//--- Backpacks
[_this,[
	"H75th_Fastpack_MCam_Grn",
	"H75th_Fastpack_Olv",
	"H75th_Fastpack_Drab",
	"H75th_Fastpack_Brwn", 
	"B_Kitbag_rgr",
	"tfw_ilbe_a_gr",
	"tfw_ilbe_gr",
	"tfw_ilbe_blade_gr",
	"tfw_ilbe_dd_gr",
	"tfw_ilbe_a_coy",
	"tfw_ilbe_coy",
	"tfw_ilbe_blade_coy",
	"tfw_ilbe_dd_coy",
	"ACE_NonSteerableParachute",
	"B_Parachute"

],true] call BIS_fnc_addVirtualBackpackCargo;

//--- Mags
[_this,[
	"rhs_mag_30Rnd_556x45_M855A1_Stanag",
	"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
	"rhs_mag_30Rnd_556x45_M855_Stanag",
	"rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red",
	"rhs_mag_30Rnd_556x45_Mk318_Stanag",
	"rhs_mag_30Rnd_556x45_Mk262_Stanag",
	"rhs_mag_30Rnd_556x45_M200_Stanag",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
	"rhs_mag_30Rnd_556x45_M855_PMAG",
	"rhs_mag_30Rnd_556x45_M855_PMAG_Tracer_Red",
	"rhs_mag_30Rnd_556x45_Mk318_PMAG",
	"rhs_mag_30Rnd_556x45_Mk262_PMAG",
	"30Rnd_556x45_Stanag",
	"30Rnd_556x45_Stanag_Tracer_Red",
	"30Rnd_556x45_Stanag_Tracer_Green",
	"30Rnd_556x45_Stanag_Tracer_Yellow",
	"rhsusf_200Rnd_556x45_box",
	"rhsusf_200rnd_556x45_mixed_box",
	"rhsusf_200rnd_556x45_M855_box",
	"rhsusf_200rnd_556x45_M855_mixed_box",
	"rhsusf_100Rnd_556x45_soft_pouch",
	"rhsusf_100Rnd_556x45_mixed_soft_pouch",
	"rhsusf_100Rnd_556x45_M855_soft_pouch",
	"rhsusf_100Rnd_556x45_M855_mixed_soft_pouch",
	"rhsusf_100Rnd_556x45_M200_soft_pouch",
	"hlc_15Rnd_9x19_B_P226",
	"hlc_15Rnd_9x19_JHP_P226",
	"hlc_15Rnd_9x19_SD_P226",
	"rhsusf_5Rnd_Slug",
	"rhsusf_5Rnd_00Buck",
	"rhsusf_20Rnd_762x51_SR25_m118_special_Mag",
	"rhsusf_20Rnd_762x51_SR25_m993_Mag",
	"rhsusf_20Rnd_762x51_SR25_m62_Mag",
	"rhsusf_100Rnd_762x51",
	"rhsusf_100Rnd_762x51_m61_ap",
	"rhsusf_100Rnd_762x51_m62_tracer",
	"rhsusf_100Rnd_762x51_m80a1epr",
	"rhsusf_100Rnd_762x51_m82_blank",
	"rhsusf_20Rnd_762x51_m118_special_Mag",
	"rhsusf_20Rnd_762x51_m993_Mag",
	"rhsusf_20Rnd_762x51_m62_Mag",
	"rhsusf_5Rnd_762x51_m118_special_Mag",
	"rhsusf_5Rnd_762x51_m993_Mag",
	"rhsusf_5Rnd_762x51_m62_Mag",
	"rhsusf_mag_10Rnd_STD_50BMG_M33",
	"rhsusf_mag_10Rnd_STD_50BMG_mk211",
	"rhs_mag_M441_HE",
	"rhs_mag_M433_HEDP",
	"rhs_mag_M781_Practice",
	"rhs_mag_M397_HET",
	"rhs_mag_m4009",
	"rhs_mag_m576",
	"rhs_mag_M585_white",
	"rhs_mag_m661_green",
	"rhs_mag_m662_red",
	"rhs_mag_m713_Red",
	"rhs_mag_m714_White",
	"rhs_mag_m715_Green",
	"rhs_mag_m716_yellow",
	"rhsusf_mag_17Rnd_9x19_FMJ",
	"rhsusf_mag_17Rnd_9x19_JHP",
	"hlc_30Rnd_9x19_B_MP5",
	"hlc_30Rnd_9x19_GD_MP5",
	"1Rnd_HE_Grenade_shell",
	"UGL_FlareWhite_F",
	"UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"UGL_FlareYellow_F",
	"UGL_FlareCIR_F",
	"1Rnd_Smoke_Grenade_shell",
	"1Rnd_SmokeRed_Grenade_shell",
	"1Rnd_SmokeGreen_Grenade_shell",
	"1Rnd_SmokeYellow_Grenade_shell",
	"1Rnd_SmokePurple_Grenade_shell",
	"1Rnd_SmokeBlue_Grenade_shell",
	"1Rnd_SmokeOrange_Grenade_shell",
	"rhsusf_5Rnd_300winmag_xm2010",
	"ACE_HuntIR_M203",
	"rhs_mag_maaws_HEAT",
	"rhs_mag_maaws_HE",
	"rhs_mag_maaws_HEDP",
	"29rnd_300BLK_STANAG",
	"29rnd_300BLK_STANAG_T",
	"29rnd_300BLK_STANAG_S",
	"rhsusf_mag_6Rnd_M781_Practice",
	"rhsusf_mag_6Rnd_m4009",
	"rhsusf_mag_6Rnd_M585_white",
	"rhsusf_mag_6Rnd_m661_green",
	"rhsusf_mag_6Rnd_m662_red",
	"rhsusf_mag_6Rnd_M713_red",
	"rhsusf_mag_6Rnd_M714_white",
	"rhsusf_mag_6Rnd_M715_green",
	"rhsusf_mag_6Rnd_M716_yellow",
	"rhsusf_mag_6Rnd_M441_HE",
	"rhsusf_mag_6Rnd_M433_HEDP",
	"rhsusf_mag_6Rnd_M397_HET",
	"rhsusf_mag_6Rnd_M576_Buckshot",
	"Laserbatteries",
	"Chemlight_blue",
	"Chemlight_green",
	"ACE_Chemlight_HiOrange",
	"ACE_Chemlight_HiRed",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"ACE_Chemlight_IR",
	"ACE_Chemlight_Orange",
	"Chemlight_red",
	"ACE_Chemlight_White",
	"Chemlight_yellow",
	"B_IR_Grenade",
	"ACE_HandFlare_Green",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_White",
	"ACE_HandFlare_Yellow",
	"SmokeShellBlue",
	"SmokeShellGreen",
	"SmokeShellOrange",
	"SmokeShellPurple",
	"SmokeShellRed",
	"SmokeShellYellow",
	"rhs_mag_m67",
	"SmokeShell",
	"ACE_M84",
	"rhs_mag_mk3a2",
	"rhsusf_m112_mag",
	"rhsusf_m112x4_mag",
	"rhsusf_mine_m14_mag",
	"ClaymoreDirectionalMine_Remote_Mag",
	"rhs_mine_M19_mag",
	"ACE_FlareTripMine_Mag",
	"DemoCharge_Remote_Mag",
	"AMP_Breaching_Charge_Mag"
],true] call BIS_fnc_addVirtualMagazineCargo;


//--- Weapons
[_this,[
	"rhs_weap_m4a1_blockII",
	"rhs_weap_m4a1_blockII_bk",
	"rhs_weap_m4a1_blockII_M203_bk",
	"rhs_weap_m4a1_blockII_KAC_bk",
	"rhs_weap_m4a1_blockII_d",
	"rhs_weap_m4a1_blockII_M203_d",
	"rhs_weap_m4a1_blockII_KAC_d",
	"rhs_weap_m4a1_blockII_M203",
	"rhs_weap_m4a1_blockII_KAC",
	"rhs_weap_m4a1_blockII_wd",
	"rhs_weap_m4a1_blockII_M203_wd",
	"rhs_weap_m4a1_blockII_KAC_wd",
	"rhs_weap_m4a1",
	"rhs_weap_M590_8RD",
	"rhs_weap_M590_5RD",
	"rhs_weap_m240B",
	"rhs_weap_m24sws",
	"rhs_weap_m24sws_d",
	"rhs_weap_m24sws_wd",
	"rhs_weap_m4a1_m320",
	"hlc_rifle_RU5562",
	"hlc_rifle_RU556",
	"hlc_rifle_bcmblackjack",
	"hlc_rifle_bcmjack",
	"hlc_rifle_m14dmr_Rail",
	"hlc_lmg_mk46",
	"hlc_lmg_mk46mod1",
	"hlc_lmg_mk48",
	"hlc_lmg_mk48mod1",
	"hlc_rifle_mk18mod0",
	"hlc_rifle_ACR_SBR_black",
	"hlc_rifle_ACR_SBR_tan",
	"hlc_rifle_ACR_full_black",
	"hlc_rifle_ACR_full_tan",
	"hlc_rifle_ACR_mid_black",
	"hlc_rifle_ACR_mid_tan",
	"hlc_rifle_ACR_Carb_black",
	"hlc_rifle_ACR_Carb_tan",
	"hlc_rifle_m14sopmod",
	"hlc_smg_MP5N",
	"rhs_weap_fim92",
	"hlc_pistol_P226R_Combat",
	"rhsusf_weap_glock17g4",
	"rhs_weap_m32",

	"rhs_weap_m249",
	"rhs_weap_m249_pip_L",
	"rhs_weap_m249_pip_L_para",
	"rhs_weap_m249_pip_L_vfg",
	"rhs_weap_m249_pip_S",
	"rhs_weap_m249_pip_S_para",
	"rhs_weap_m249_pip_S_vfg",
	"rhs_weap_m249_pip",

	"rhs_weap_sr25_ec",
	"rhs_weap_sr25_ec_d",
	"rhs_weap_sr25_ec_wd",

	"rhs_weap_maaws",
	"rhs_weap_M136_hp",
	"rhs_weap_M136_hedp",
	"rhs_weap_M136",
	"rhs_weap_m72a7",
	"rhs_weap_M320",

	"rhs_weap_XM2010",
	"rhs_weap_XM2010_wd",
	"rhs_weap_XM2010_d",
	"rhs_weap_XM2010_sa",
	"rhs_weap_M107",
	"rhs_weap_M107_d",
	"rhs_weap_M107_w"
],true] call BIS_fnc_addVirtualWeaponCargo;

//--- Items and Stuff
//--- ACE
[_this,[
	"ACE_wirecutter",
	"ACE_EntrenchingTool",
	"ACE_MapTools",
	"ACE_fieldDressing",
	"ACE_packingBandage",
	"ACE_elasticBandage",
	"ACE_tourniquet",
	"ACE_morphine",
	"ACE_atropine",
	"ACE_epinephrine",
	"ACE_plasmaIV",
	"ACE_plasmaIV_500",
	"ACE_plasmaIV_250",
	"ACE_bloodIV",
	"ACE_bloodIV_500",
	"ACE_bloodIV_250",
	"ACE_salineIV",
	"ACE_salineIV_500",
	"ACE_salineIV_250",
	"ACE_quikclot",
	"ACE_surgicalKit",
	"ACE_bodyBag",
	"ACE_Sandbag_empty",
	"ACE_DefusalKit",
	"ACE_EarPlugs",
	"ACE_Flashlight_MX991",
	"ACE_LIB_LadungPM",
	"ACE_LIB_FireCord",
	"ACE_adenosine",
	"ACE_atropine",
	"ACE_ATragMX",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_quikclot",
	"ACE_SpraypaintBlack",
	"ACE_bloodIV",
	"ACE_bloodIV_250",
	"ACE_bloodIV_500",
	"ACE_SpraypaintBlue",
	"ACE_bodyBag",
	"ACE_CableTie",
	"ACE_Chemlight_Shield",
	"ACE_DAGR",
	"ACE_DefusalKit",
	"ACE_EarPlugs",
	"ACE_EntrenchingTool",
	"ACE_epinephrine",
	"ACE_Flashlight_MX991",
	"ACE_SpraypaintGreen",
	"ACE_HuntIR_monitor",
	"ACE_IR_Strobe_Item",
	"ACE_Kestrel4500",
	"ACE_M26_Clacker",
	"ACE_Clacker",
	"ACE_Flashlight_XL50",
	"ACE_MapTools",
	"ACE_microDAGR",
	"MineDetector",
	"ACE_morphine",
	"ACE_packingBandage",
	"ACE_personalAidKit",
	"ACE_plasmaIV",
	"ACE_plasmaIV_250",
	"ACE_plasmaIV_500",
	"ACE_RangeCard",
	"ACE_SpraypaintRed",
	"ACE_salineIV",
	"ACE_salineIV_250",
	"ACE_salineIV_500",
	"adv_aceSplint_splint",
	"adv_aceCPR_AED",
	"ACE_Sandbag_empty",
	"tfw_rf3080Item",
	"ACE_surgicalKit",
	"ToolKit",
	"ACE_tourniquet",
	"ACE_UAVBattery",
	"tfw_blade",
	"tfw_whip",
	"tfw_dd",
	"ACE_wirecutter",
	"ItemcTabHCam",
	"MRH_BluForTransponder",
	"ACE_SpottingScope",
	"ACE_Tripod",
	"MRH_TacticalDisplay",
	"MRH_FoldedSatcomAntenna",
	
	//--- nvg
	"ANPVS15_Black",
	"gpn18",
	
	//--- binoc types
	"Laserdesignator",
	"Laserdesignator_01_khk_F",
	"ACE_Vector",

	
	//--- stuff
	"ItemMap",
	"ItemCompass",
	"ACE_Altimeter",
	"tf_anprc152",
	"ItemGPS",
	"ItemcTab",
	"ItemWatch",
	"ItemAndroid",

	
	//--- attachments
	"rhsusf_acc_T1_high",
	"rhsusf_acc_T1_low",
	"rhsusf_acc_ACOG2_USMC",
	"rhsusf_acc_ACOG3_USMC",
	"rhsusf_acc_ACOG_USMC",
	"rhsusf_acc_EOTECH",
	"rhsusf_acc_g33_T1",
	"rhsusf_acc_g33_xps3",
	"rhsusf_acc_g33_xps3_tan",
	"rhsusf_acc_ELCAN",
	"rhsusf_acc_ELCAN_ard",
	"rhsusf_acc_ACOG",
	"rhsusf_acc_ACOG2",
	"rhsusf_acc_ACOG3",
	"rhsusf_acc_eotech_552",
	"rhsusf_acc_eotech_552_d",
	"rhsusf_acc_eotech_552_wd",
	"rhsusf_acc_compm4",
	"rhsusf_acc_su230",
	"rhsusf_acc_su230_c",
	"rhsusf_acc_su230_mrds",
	"rhsusf_acc_su230_mrds_c",
	"rhsusf_acc_su230a",
	"rhsusf_acc_su230a_c",
	"rhsusf_acc_su230a_mrds",
	"rhsusf_acc_su230a_mrds_c",
	"rhsusf_acc_ACOG_RMR",
	"rhsusf_acc_ACOG_d",
	"rhsusf_acc_ACOG_wd",
	"rhsusf_acc_eotech_xps3",

	"ACE_optic_Arco_2D",
	"ACE_optic_Arco_PIP",
	"ACE_optic_LRPS_2D",
	"ACE_optic_LRPS_PIP",
	"ACE_optic_SOS_2D",
	"ACE_optic_SOS_PIP",
	"ACE_optic_MRCO_2D",
	"optic_AMS",
	"optic_AMS_khk",
	"optic_AMS_snd",
	"HLC_Optic_Docter_CADEX",
	"HLC_optic_HP",
	"HLC_Optic_Romeo1_RX",
	"HLC_optic_Siglite",
	"HLC_optic_ATT",
	"HLC_optic_XS",
	"HLC_optic_VTAC",
	"HLC_optic_stavenhagen",

	"rhsusf_acc_LEUPOLDMK4_2_d",
	"rhsusf_acc_LEUPOLDMK4_wd",
	"rhsusf_acc_LEUPOLDMK4_d",
	"rhsusf_acc_LEUPOLDMK4_2",
	"rhsusf_acc_LEUPOLDMK4",
	"rhsusf_acc_premier",
	"rhsusf_acc_premier_anpvs27",
	"rhsusf_acc_premier_low",
	"rhsusf_acc_M8541_low_wd",
	"rhsusf_acc_M8541_low_d",
	"rhsusf_acc_M8541_low",
	"rhsusf_acc_M8541",
	"rhs_optic_maaws",

	"rhsusf_acc_anpeq15side",
	"rhsusf_acc_anpeq15_top",
	"rhsusf_acc_anpeq15_wmx",
	"rhsusf_acc_anpeq15_wmx_light",
	"rhsusf_acc_anpeq15side_bk",
	"rhsusf_acc_anpeq15_bk_top",
	"rhsusf_acc_anpeq15",
	"rhsusf_acc_anpeq15_light",
	"rhsusf_acc_anpeq15_bk",
	"rhsusf_acc_anpeq15_bk_light",
	"rhsusf_acc_anpeq15A",
	"rhsusf_acc_anpeq16a",
	"rhsusf_acc_anpeq16a_light",
	"rhsusf_acc_anpeq16a_top",
	"rhsusf_acc_anpeq16a_light_top",
	"ACE_acc_pointer_green",
	"acc_pointer_IR",
	"rhsusf_acc_M952V",

	"hlc_muzzle_556NATO_M42000",
	"hlc_muzzle_556NATO_KAC",
	"hlc_muzzle_556NATO_rotexiiic_grey",
	"hlc_muzzle_556NATO_rotexiiic_tan",
	"hlc_muzzle_300blk_KAC",
	"hlc_muzzle_Octane9",
	"rhsusf_acc_SFMB556",
	"rhsusf_acc_SF3P556",

	"rhsusf_acc_grip2",
	"rhsusf_acc_grip2_tan",
	"rhsusf_acc_grip2_wd",
	"bipod_01_F_blk",
	"rhsusf_acc_grip1",
	"rhsusf_acc_harris_bipod",
	"hlc_acc_DBALPL",
	"hlc_acc_DBALPL_FL",
	"hlc_acc_TLR1",

	"rhsusf_acc_M2010S_wd",
	"rhsusf_acc_M2010S",
	"rhsusf_acc_m24_silencer_black",
	"rhsusf_acc_m24_silencer_d",
	"rhsusf_acc_m24_silencer_wd",
	"rhsusf_acc_M2010S_d",
	"rhsusf_acc_M2010S_sa",
	"rhsusf_acc_sr25S",
	"rhsusf_acc_sr25S_d",
	"rhsusf_acc_sr25S_wd",

	
	//--- uniforms
	"CRYE_V2_Full",
	"CRYE_V3_Full",
	"CRYE_V4_Full",
	"CRYE_V2_Sleeved",
	"CRYE_V3_Sleeved",
	"CRYE_V4_Sleeved",
	"CRYEG3_V3",
	"CRYEG3_V1",
	"CRYEG3_V2",
	"rhs_uniform_cu_ocp",
	"U_B_Wetsuit",
	"CRYE_V1_Full",
	"CRYE_V1_Sleeved",
	"FIR_Fighter_Pilot_Nomex",
	"FIR_Fighter_Pilot_Nomex2",
	"FIR_Fighter_Pilot_Nomex3",
	"FIR_Fighter_Pilot_Nomex4",
	"FIR_Fighter_Pilot_Nomex5",
	"FIR_Fighter_Pilot_Nomex6",
	"FIR_Fighter_Pilot_Nomex7",


	
	//--- vests
	"cpc_weaponsbelt_rngr",
	"cpc_tlbelt_rngr",
	"cpc_medicalbelt_rngr",
	"cpc_lightbelt_rngr",
	"cpc_Fastbelt_rngr",
	"cpc_communicationsbelt_rngr",
	"cpc_weaponsbelt_coy",
	"cpc_tlbelt_coy",
	"cpc_medicalbelt_coy",
	"cpc_lightbelt_coy",
	"cpc_Fastbelt_coy",
	"cpc_communicationsbelt_coy",
	"V_RebreatherB",
	"FIR_pilot_vest",


	"V_DeckCrew_red_F",
	"V_DeckCrew_yellow_F",
	"V_DeckCrew_white_F",
	"V_DeckCrew_blue_F",
	"V_DeckCrew_green_F",


	
	//--- Headwear
	"OpsC_Cov_Goggles_Off",
	"OpsC_Cov_Full",
	"OpsC_Covered",
	"OpsC_Covered2",
	"OpsC_Painted",
	"OpsC_Med",
	"OpsC_Uncov_Full",
	"OpsC_Uncov_Goggles",
	"OpsC_Uncov_Goggle_Off",
	"OpsC_Uncov_Shemagh",
	"OpsC_Uncovered",
	"FIR_HGU55PJ",
	"FIR_JHMCS",
	"FIR_JHMCS_II",
	
	"2nd_Battalion_CPT_Beret",
	"2nd_Battalion_Enlisted_Beret",
	"2nd_Battalion_COL_Beret",
	"2nd_Battalion_1LT_Beret",
	"2nd_Battalion_2LT_Beret",
	"2nd_Battalion_MAJ_Beret",
	"2nd_Battalion_LTC_Beret",
	
	"soar_beret_1lt",
	"soar_beret_2lt",
	"soar_beret_cpt",
	"soar_beret_wo1",
	"soar_beret_wo2",
	"soar_beret_wo3",
	"soar_beret_wo4",
	"soar_beret_wo5",
	"soar_beret_enlisted",

	"rhsusf_hgu56p",
	"rhsusf_hgu56p_mask",
	"rhsusf_hgu56p_visor",
	"rhsusf_hgu56p_visor_mask",
	"rhsusf_hgu56p_black",
	"rhsusf_hgu56p_mask_black",
	"rhsusf_hgu56p_visor_black",
	"rhsusf_hgu56p_visor_mask_black",
	//--- goggles, glasses, facewear
	"Oakley_Goggles_MCam",
	"Oakley_Goggles_Blk",
	"Oakley_Goggles_DTan",
	"Oakley_Goggles_MCam",
	"H75th_Foretex",

	"H75th_Neck_Plain_Atacs",
	"H75th_Neck_Plain_Atacs2",
	"H75th_Neck_Plain2",
	"H75th_Neck_Plain3",


	"UA_Thermals_Blk_GPS",
	"UA_Thermals_Grn_GPS",
	"UA_Thermals_Blk",
	"UA_Thermals_Grn",

	"rhs_googles_black",
	"rhs_googles_yellow",
	"rhs_googles_clear",
	"rhs_googles_orange",


	"HTac_Goggles_Blk_Ylw",
	"HTac_Goggles_Tan_Clr",

	"FIR_HGU55PJ_Visor_Black_down",
	"FIR_HGU55PJ_Visor_Black_up",
	"FIR_HGU55PJ_Visor_clear_down",
	"FIR_HGU55PJ_Visor_clear_up",
	
	"G_B_Diving"

],true] call BIS_fnc_addVirtualItemCargo;	

["Open",false] spawn BIS_fnc_arsenal;
